### ISSUE TITLE
В автопоиск на github попадают неверные репозитории

### ISSUE THREAD

**Issue by andreevlex** [allustin/awesome-1c#14]
В файле [https://github.com/allustin/awesome-1c/blob/master/data/README.md](https://github.com/allustin/awesome-1c/blob/master/data/README.md)
В раздел "Репозитории с 1С гарантировано" попала ссылка на [ctuning/ck-crowdtuning-platforms](https://github.com/ctuning/ck-crowdtuning-platforms), но кода `bsl` или `os` там нет.

**Comment by andreevlex** [comment]
Еще нашел не соотвествие [Eurospider/OpenBSD-firewall](https://github.com/Eurospider/OpenBSD-firewall) в разделе "Репозитории с 1С гарантировано".
Поиск по репозиторию выдал один файл с расширением `.os`

**Comment by nixel2007** [comment]
К сожалению сейчас все файлы с расширением bsl и os ложатся в язык 1C:Enterprise, даже не имеющие отношения к 1с. И пока кто-то не добавит новый язык с теми же расширениями в лингвист так и будет :(

**Comment by nixel2007** [comment]
По обоим ссылкам есть файлы с расширением os
