### ISSUE TITLE
Перестал обновляться автоматический список реп и пользователей с 1 сентября 2016 г

### ISSUE THREAD

**Issue by kuntashov** [allustin/awesome-1c#8]
Сейчас автоматический список пустой и по истории видно, что это началось 1 сентября:

https://github.com/allustin/awesome-1c/commit/6b216be0d7fca7cfb708990085ca0c6f06ea25bf#diff-5c42c70225607b7aec08db0e7ae11da3

Скрипт парсинга не проверял, но вполне вероятно, что это он сломался, т.к. в начале сентября github обновления начал выкатывать, наверняка что-то и в верстке результатов поиска могло поменяться.

**Comment by allustin** [comment]
Враги... Поломали. Надо проверить - спасибо @kuntashov

**Comment by kuntashov** [comment]
@allustin погуглил/поразбирался, сломалась не верстка, почему-то через раз гитхаб вместо результатов поиска выдает "We could not perform this search", причем если я не залогинен - то всегда такая ошибка. Если залогинен - то при изменении поискового запроса иногда результат выдается, а если повторить - снова такая же ошибка. Воспроизводится стабильно.

Есть подозрение, что это может так работать системы защиты от ддоса.

Вот здесь народ еще месяц назад с таким столкнулся http://jakubdziworski.github.io/tools/2016/08/26/github-code-advances-search-programmers-goldmine.html#comment-2870253811 и там в комментариях пишут, что это либо баг, либо защита от ддоса.

Также пока искал я подумал, что теперь можно искать уже не по расширению, а по языку - так должно быть эффективнее:

![lang_bsl](https://cloud.githubusercontent.com/assets/1042299/18928994/42179172-85cb-11e6-930a-0ca62531f2d2.png)

Но обсуждаемую проблему это не меняет :(

**Comment by allustin** [comment]
нашел проблему - оказывается поменялся формат результатов. Вроде как результаты поиска - подгружаются "реактивно" через JSON в уже сформированную страницу.

**Comment by kuntashov** [comment]
@allustin у меня по-прежнему при поиске _в ручном режиме_ результат все равно не выводится, вместо этого через раз выводится ошибка, как я описал выше.

Если на самом деле "реактивно" осуществляется, тогда вместо просто загрузки страницы через http ее можно получать при помощи pantomjs, в нем js выполняется.
